version: "3.9"

services:

  backend:
    build: ./Backend
    container_name: kradtravel_backend
    restart: always

    ports:
      - "7400:3400"

    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    container_name: kradtravel_frontend
    restart: always

    ports:
      - "6400:80"

    depends_on:
      - backend